### ISSUE TITLE
[Task] Docker Restart Policy

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#244]
Task | Docker Restart Policy
----------|----------
Task Title | Docker Restart Policy
User Story | 
Epic | #213 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Description | Docker containers should restart on fatal errors
Business Need (the why): | 
Applications or Systems impacted | 
Dependencies | 
Assumptions |

**Comment by jbobo** [comment]
When we're ready to implement this we just need to add `restart: unless-stopped` to our Dockerfiles. Like this:

```
version: '3'
services:
    my-service:
        restart: unless-stopped
```
